# Generated by Django 5.2 on 2025-05-01 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_image_options_alter_product_options'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='placeholders/default/', verbose_name='Изображение заглушка')),
                ('is_active', models.BooleanField(default=True, help_text='Использовать это изображение как заглушку', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Стандартная заглушка',
                'verbose_name_plural': 'Стандартные заглушки',
            },
        ),
        migrations.CreateModel(
            name='CategoryPlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='placeholders/', verbose_name='Изображение заглушка')),
                ('is_active', models.BooleanField(default=True, help_text='Использовать это изображение как заглушку', verbose_name='Активно')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholders', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Заглушка категории',
                'verbose_name_plural': 'Заглушки категорий',
            },
        ),
    ]
