# Generated by Django 5.2 on 2025-05-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_defaultplaceholder_categoryplaceholder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
