# Generated by Django 5.2 on 2025-04-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_preview',
            field=models.BooleanField(default=False, verbose_name='Использовать как превью'),
        ),
    ]
